#! /bin/bash -x

is_mac() { [ $OSTYPE = 'darwin12' ]; }

is_linux() { [ $OSTYPE = 'linux-gnu' ]; }

if is_mac; then
    if [ ! `which brew` ]; then
        echo "Install homebrew"
        ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go)"
    fi
    if [ ! `which wget` ]; then
        echo "Install wget"
        brew install wget
    fi
    if [ ! `which htop` ]; then
        echo "Install htop"
        brew install htop
        # sudo chown root:wheel /usr/local/Cellar/htop-osx/0.8.2.1/bin/htop
        # sudo chmod u+s /usr/local/Cellar/htop-osx/0.8.2.1/bin/htop
    fi
    # brew install emacs --cocoa
    if [ ! `which greadlink` ]; then
        echo "Install coreutils"
        brew install coreutils
        echo "Install Emacs"
        brew install emacs --cocoa
        mkdir -p ~/Applications
        brew linkapps
    fi

    if [ ! `which rlwrap` ]; then
        echo "Install rlwrap"
        brew install rlwrap
    fi

    if [ ! `which virtualenv` ]; then
        echo "Install virtualenv"
        # sudo easy_install virtualenv
    fi

    if [ ! `which pip` ]; then
        echo "Install pip"
        sudo easy_install pip
    fi

    if [ ! `which ipython` ]; then
        echo "Install ipython"
        sudo pip install ipython
    fi
fi

if is_linux; then
    ABSOLUTE_PATH=$(readlink -f $0)
    DOTFILES="${ABSOLUTE_PATH%/*}"
else
    DOTFILES="/Users/feng/dotfiles"
fi

mkdir -p ~/.ssh
mkdir -p ~/.config
mkdir -p ~/bin

rm -rf ~/.Xresources
rm -rf ~/.config/awesome
rm -rf ~/.emacs.d
rm -rf ~/.fonts
rm -rf ~/.gitconfig
rm -rf ~/.tmux.conf
rm -rf ~/.vim
rm -rf ~/.vimrc
rm -rf ~/.vimrc
rm -rf ~/.xinitrc
rm -rf ~/.zshrc

if is_linux; then
    ln -sf $DOTFILES/awesome ~/.config/awesome
    ln -sf $DOTFILES/chrome ~/bin/
    ln -sf $DOTFILES/evilvte/evilvte ~/bin/
    ln -sf $DOTFILES/tmux.conf ~/.tmux.conf
    ln -sf $DOTFILES/xinitrc ~/.xinitrc
    ln -sf $DOTFILES/xresources ~/.Xresources
else
    # show full path in finder's title
    defaults write com.apple.finder _FXShowPosixPathInTitle -bool YES
    defaults write com.apple.dashboard mcx-disabled -boolean YES
    killall Dock
    # cp $DOTFILES/osx/me.shenfeng.tmpfs.plist ~/Library/LaunchAgents

    # http://blog.alutam.com/2012/04/01/optimizing-macos-x-lion-for-ssd/#hibernation
    sudo cp $DOTFILES/osx/me.shenfeng.noatime.plist /Library/LaunchDaemons/
    sudo chown root:wheel /Library/LaunchDaemons/me.shenfeng.noatime.plist


    # tmpfs for osx
    # launchctl unload -w ~/Library/LaunchAgents/me.shenfeng.tmpfs.plist
    # launchctl load -w ~/Library/LaunchAgents/me.shenfeng.tmpfs.plist

    # disable spotlight
    sudo launchctl unload -w /System/Library/LaunchDaemons/com.apple.metadata.mds.plist
    # enable it
    # sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.metadata.mds.plist

    # http://superuser.com/questions/460658/why-os-x-use-swap-when-there-is-lots-of-inactive-memory
    # disable swap in osx
    # sudo launchctl unload -w /System/Library/LaunchDaemons/com.apple.dynamic_pager.plist

    # disable sleep mode
    # https://discussions.apple.com/thread/4492672?start=0&tstart=0
    # sudo pmset -a hibernatefile /dev/null
    # sudo pmset -a hibernatemode 0
fi

mkdir -p $DOTFILES/emacs.d/vendor

ln -sf $DOTFILES/ackrc ~/.ackrc
ln -sf $DOTFILES/emacs.d ~/.emacs.d
ln -sf $DOTFILES/fonts ~/.fonts
ln -sf $DOTFILES/fonts.conf ~/.fonts.conf
ln -sf $DOTFILES/gitconfig ~/.gitconfig
ln -sf $DOTFILES/ssh_config ~/.ssh/config
ln -sf $DOTFILES/vim ~/.vim
ln -sf $DOTFILES/vimrc ~/.vimrc
ln -sf $DOTFILES/zshrc ~/.zshrc
ln -sf $DOTFILES/pyline ~/bin/pyline


if [ ! -d ~/dotfiles/zsh/zsh-completions ]; then
    cd $DOTFILES/zsh/
    git clone git://github.com/zsh-users/zsh-completions.git
fi

if [ ! -d ~/dotfiles/iTerm-2-Color-Themes ]; then
    cd $DOTFILES/
    git clone git://github.com/baskerville/iTerm-2-Color-Themes.git
fi

rm -f ~/.zcompdump; compinit    #  compinit is zsh

# install vcprompt
if [ ! -f ~/bin/vcprompt ]; then
    echo "install vcprompt";
    cd /tmp;
    wget -c https://github.com/djl/vcprompt/raw/master/bin/vcprompt --no-check-certificate
    chmod +x vcprompt;
    mv vcprompt ~/bin/
fi

if [ ! -f ~/bin/s ]; then
    echo "install ack-grep";
    cd /tmp/
    wget -c http://betterthangrep.com/ack-standalone -O ack-grep
    chmod +x ack-grep
    mv ack-grep ~/bin/s
fi

if [ ! -f ~/.emacs.d/vendor/js2-mode.el ]; then
    cd ~/.emacs.d/vendor/
    wget -c https://raw.github.com/mooz/js2-mode/master/js2-mode.el
fi

# Socks proxy, more handy than the above, no setup on the server
# ssh -C2qTnN -D localhost:3218 username@server

# install lein
if [ ! -f ~/bin/lein ]; then
    echo "install lein";
    cd /tmp;
    wget -c https://github.com/technomancy/leiningen/raw/stable/bin/lein --no-check-certificate
    chmod +x lein;
    mv lein ~/bin/
fi

if [ ! -f ~/bin/wrk ]; then
    echo "Install wrk"
    cd /tmp
    git clone git://github.com/wg/wrk.git
    cd wrk
    make
    cp wrk ~/bin/
fi

if ! is_linux; then
    mkdir -p  ~/Applications
    if [ ! -d ~/Applications/iTerm.app ]; then
        cd /tmp/
        wget -c https://iterm2.googlecode.com/files/iTerm2-1_0_0_20130319.zip
        mkdir -p ~/Applications
        tar xf iTerm2-1_0_0_20130319.zip
        mv iTerm.app ~/Applications
    fi
fi

if [ ! -d ~/bin/go ]; then
    cd /tmp
    GOLANG=go1.1beta2.darwin-amd64.tar.gz
    wget -c https://go.googlecode.com/files/$GOLANG
    tar xf $GOLANG
    mv go ~/bin
fi

# install mysql, untar mysql and ln to ~/bin/mysql
#  ./scripts/mysql_install_db --basedir=/Users/linna/Downloads/mysql-5.6.11-osx10.7-x86_64 --defaults-file=~/dotfiles/my-dev.cnf
#  ./bin/mysqld --defaults-file=~/dotfiles/my-dev.cnf
# ./bin/mysql --host 127.0.0.1 -uroot
# CREATE USER feng@'%' IDENTIFIED BY ''
# GRANT ALL PRIVILEGES ON *.* TO 'feng'@'%' with grant option;
# flush privileges

exit

show master status
show slave status
start slave
stop slave 
reset slave
CHANGE MASTER TO
    MASTER_HOST='192.168.1.101',
    MASTER_USER='feng',
    MASTER_PASSWORD='',
    MASTER_LOG_FILE='mysql-bin.000004',
    MASTER_LOG_POS=800;




# 010109248 gehua.net user id
# rm -f ~/.zcompdump; compinit


# google.com.             283     IN      A       74.125.128.101
# google.com.             283     IN      A       74.125.128.100
# google.com.             283     IN      A       74.125.128.139
# google.com.             283     IN      A       74.125.128.138
# google.com.             283     IN      A       74.125.128.113
# google.com.             283     IN      A       74.125.128.102
# http://203.208.45.209/
# 203.208.46.145
